/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResidentsRouteImport } from './routes/residents'
import { Route as OccurrencesRouteImport } from './routes/occurrences'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DeliveriesRouteImport } from './routes/deliveries'
import { Route as AdminOccurrencesRouteImport } from './routes/admin-occurrences'
import { Route as IndexRouteImport } from './routes/index'

const ResidentsRoute = ResidentsRouteImport.update({
  id: '/residents',
  path: '/residents',
  getParentRoute: () => rootRouteImport,
} as any)
const OccurrencesRoute = OccurrencesRouteImport.update({
  id: '/occurrences',
  path: '/occurrences',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveriesRoute = DeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOccurrencesRoute = AdminOccurrencesRouteImport.update({
  id: '/admin-occurrences',
  path: '/admin-occurrences',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-occurrences': typeof AdminOccurrencesRoute
  '/deliveries': typeof DeliveriesRoute
  '/login': typeof LoginRoute
  '/occurrences': typeof OccurrencesRoute
  '/residents': typeof ResidentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-occurrences': typeof AdminOccurrencesRoute
  '/deliveries': typeof DeliveriesRoute
  '/login': typeof LoginRoute
  '/occurrences': typeof OccurrencesRoute
  '/residents': typeof ResidentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-occurrences': typeof AdminOccurrencesRoute
  '/deliveries': typeof DeliveriesRoute
  '/login': typeof LoginRoute
  '/occurrences': typeof OccurrencesRoute
  '/residents': typeof ResidentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-occurrences'
    | '/deliveries'
    | '/login'
    | '/occurrences'
    | '/residents'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-occurrences'
    | '/deliveries'
    | '/login'
    | '/occurrences'
    | '/residents'
  id:
    | '__root__'
    | '/'
    | '/admin-occurrences'
    | '/deliveries'
    | '/login'
    | '/occurrences'
    | '/residents'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminOccurrencesRoute: typeof AdminOccurrencesRoute
  DeliveriesRoute: typeof DeliveriesRoute
  LoginRoute: typeof LoginRoute
  OccurrencesRoute: typeof OccurrencesRoute
  ResidentsRoute: typeof ResidentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/residents': {
      id: '/residents'
      path: '/residents'
      fullPath: '/residents'
      preLoaderRoute: typeof ResidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/occurrences': {
      id: '/occurrences'
      path: '/occurrences'
      fullPath: '/occurrences'
      preLoaderRoute: typeof OccurrencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliveries': {
      id: '/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof DeliveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-occurrences': {
      id: '/admin-occurrences'
      path: '/admin-occurrences'
      fullPath: '/admin-occurrences'
      preLoaderRoute: typeof AdminOccurrencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminOccurrencesRoute: AdminOccurrencesRoute,
  DeliveriesRoute: DeliveriesRoute,
  LoginRoute: LoginRoute,
  OccurrencesRoute: OccurrencesRoute,
  ResidentsRoute: ResidentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
