/**
 * Tailwind CSS configuration for Serene Professional design system
 * See DESIGN.MD for full design tokens and rationale
 */
import type { Config } from 'tailwindcss'
import typography from '@tailwindcss/typography'

export default {
  content: [
    './src/**/*.{js,ts,jsx,tsx}',
    './index.html',
  ],
  theme: {
    fontFamily: {
      sans: ['Manrope', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      headline: ['Manrope', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      body: ['Manrope', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      label: ['Manrope', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      caption: ['Manrope', 'ui-sans-serif', 'system-ui', 'sans-serif'],
    },
    extend: {
      colors: {
        surface: '#f9f9ff',
        'surface-dim': '#cfdaf2',
        'surface-bright': '#f9f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f3ff',
        'surface-container': '#e7eeff',
        'surface-container-high': '#dee8ff',
        'surface-container-highest': '#d8e3fb',
        'on-surface': '#111c2d',
        'on-surface-variant': '#44474e',
        'inverse-surface': '#263143',
        'inverse-on-surface': '#ecf1ff',
        outline: '#74777f',
        'outline-variant': '#c4c6cf',
        'surface-tint': '#4a5f86',
        primary: '#40557b',
        'on-primary': '#ffffff',
        'primary-container': '#586d95',
        'on-primary-container': '#ebefff',
        'inverse-primary': '#b1c7f4',
        secondary: '#5a5f63',
        'on-secondary': '#ffffff',
        'secondary-container': '#dce0e5',
        'on-secondary-container': '#5e6367',
        tertiary: '#525557',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#6a6d6f',
        'on-tertiary-container': '#eef0f2',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#d7e3ff',
        'primary-fixed-dim': '#b1c7f4',
        'on-primary-fixed': '#001b3f',
        'on-primary-fixed-variant': '#31476c',
        'secondary-fixed': '#dfe3e8',
        'secondary-fixed-dim': '#c3c7cc',
        'on-secondary-fixed': '#171c20',
        'on-secondary-fixed-variant': '#42474b',
        'tertiary-fixed': '#e0e3e5',
        'tertiary-fixed-dim': '#c4c7c9',
        'on-tertiary-fixed': '#191c1e',
        'on-tertiary-fixed-variant': '#444749',
        background: '#f9f9ff',
        'on-background': '#111c2d',
        'surface-variant': '#d8e3fb',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
        card: '2rem', // for large cards
        cardxl: '2.5rem',
      },
      spacing: {
        xs: '4px',
        sm: '12px',
        md: '24px',
        lg: '48px',
        xl: '80px',
        base: '8px',
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-md': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-sm': ['14px', { lineHeight: '1.4', fontWeight: '600', letterSpacing: '0.05em' }],
        caption: ['12px', { lineHeight: '1.4', fontWeight: '500' }],
      },
      boxShadow: {
        card: '0 20px 50px rgba(0,0,0,0.05)',
        soft: '0 8px 24px rgba(30,90,72,0.08)',
        'soft-xl': '0 22px 44px rgba(30,90,72,0.1), 0 6px 18px rgba(23,58,64,0.08)',
        'soft-card': '0 18px 34px rgba(30,90,72,0.1), 0 4px 14px rgba(23,58,64,0.06)',
      },
    },
  },
  plugins: [typography],
} satisfies Config
